// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc100.Team100Robot;

import org.usfirst.frc100.Team100Robot.commands.*;
import org.usfirst.frc100.Team100Robot.commands.Elevator.ElevatorMoveToSetpoint;
import org.usfirst.frc100.Team100Robot.commands.Elevator.ElevatorPageDown;
import org.usfirst.frc100.Team100Robot.commands.Elevator.ElevatorPageUp;
import org.usfirst.frc100.Team100Robot.commands.Shoulder.ShoulderDown;
import org.usfirst.frc100.Team100Robot.commands.Shoulder.ShoulderUp;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());

    private Joystick leftStick;
    private Joystick rightStick;
    private Joystick manipulatorControl;
    
    private JoystickButton shiftLow;
    private JoystickButton shiftHigh;
    private JoystickButton spitCargo;
    private JoystickButton hatchUp;
    private JoystickButton hatchDown;
    private JoystickButton intakeCargo;
    private JoystickButton cargoUp;
    private JoystickButton cargoDown;
    private JoystickButton climberToggle;
    private JoystickButton hatchClamp;
    private JoystickButton elevatorStageUp;
    private JoystickButton hatchRelease;
    private JoystickButton elevatorStageDown;

    public OI() {

        /*
         * INIT Joysticks
         */
        leftStick = new Joystick(0);
        rightStick = new Joystick(1);
        manipulatorControl = new Joystick(2);

        
        /* 
         * Joystick 0 (Left Stick)
         */
        spitCargo = new JoystickButton(leftStick, 1);
        spitCargo.whenPressed(new SpitCargo());

        shiftLow = new JoystickButton(leftStick, 3);
        shiftLow.whenPressed(new LowGear());
        
        hatchUp = new JoystickButton(leftStick, 4);
 
        hatchDown = new JoystickButton(leftStick, 5);

        //Joystick 1 (Right Stick)
        intakeCargo = new JoystickButton(rightStick, 1);
        
        shiftHigh = new JoystickButton(rightStick, 3);
        shiftHigh.whenPressed(new HighGear());
        
        cargoUp = new JoystickButton(rightStick, 4);
        cargoUp.whenPressed(new ShoulderUp());
 
        cargoDown = new JoystickButton(rightStick, 5);
        cargoDown.whenPressed(new ShoulderDown());

        //Joystick 2 (Manipulator Control)
        climberToggle = new JoystickButton(manipulatorControl, 4);
 
        hatchClamp = new JoystickButton(manipulatorControl, 5);

        elevatorStageUp = new JoystickButton(manipulatorControl, 6);

        hatchRelease = new JoystickButton(manipulatorControl, 7);

        elevatorStageDown = new JoystickButton(manipulatorControl, 8);

        elevatorStageUp.whenPressed(new ElevatorPageUp());
        elevatorStageDown.whenPressed(new ElevatorPageDown());




        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("DriveCMD", new Drive());
        SmartDashboard.putData("HighGear", new HighGear());
        SmartDashboard.putData("LowGear", new LowGear());
    }

    public Joystick getLeftStick() {
        return leftStick;
    }

    public Joystick getRightStick() {
        return rightStick;
    }

    public Joystick getManipulatorControl() {
        return manipulatorControl;
    }

}

