// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc100.Team100Robot.subsystems;

import edu.wpi.first.wpilibj.command.Subsystem;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import org.usfirst.frc100.Team100Robot.Constants;

import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.VictorSP;

/**
 *
 */
public class CargoPickup extends Subsystem {

    private WPI_TalonSRX tiltCargoFloorPickup;
    private VictorSP rollerCargoFloorPickup;
    private Solenoid cargoGroundPickup;

    public CargoPickup() {
        tiltCargoFloorPickup = new WPI_TalonSRX(Constants.CARGO_PICKUP_TILT_PWM);

        rollerCargoFloorPickup = new VictorSP(Constants.CARGO_PICKUP_ROLLER_PWM);
        addChild("RollerCargoFloorPickup", rollerCargoFloorPickup);
        rollerCargoFloorPickup.setInverted(false);
        
        cargoGroundPickup = new Solenoid(Constants.PCM_CANID, Constants.CARGO_GROUND_PICKUP_PCMID);
        addChild("CargoGroundPickup", cargoGroundPickup);
    }

    @Override
    public void initDefaultCommand() {
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
    }
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

