// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc100.Team100Robot.subsystems;


import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Preferences;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;

import org.usfirst.frc100.Team100Robot.Constants;
import org.usfirst.frc100.Team100Robot.commands.Elevator.ElevatorAtSetpoint;
import org.usfirst.frc100.Team100Robot.commands.Elevator.ElevatorMoveToSetpoint;
import org.usfirst.frc100.Team100Robot.commands.Elevator.ElevatorTeleop;
import org.usfirst.frc100.Team100Robot.commands.Elevator.Homing.ElevatorHomingInit;


public class Elevator extends Subsystem {


    public WPI_TalonSRX elevatorMaster;
    public WPI_VictorSPX elevatorFollower;
    public DigitalInput lowerLimitSwitch = new DigitalInput(0);
    public DigitalInput upperLimitSwitch = new DigitalInput(1);
    public DigitalInput intermediateLimitSwitch = new DigitalInput(2);
    public DigitalInput intermediateDownLimitSwitch = new DigitalInput(3);
    public int setpoint;

    public int setpointLevel = 0;
    /**
     * Enum for possible homing states of the elevator
     */
    public enum homingStates{
        INIT,ELEV_GOING_DOWN,ELEV_AT_LIMIT_SWITCH,ELEV_RISING,COMPLETE,FATAL
    }
    /**
     * The homing state of the elevator
     */
    public homingStates hs;
    /**
     * Possible states for the elevator to be in
     */
    public enum States{
        AT_SETPOINT,MOVE_TO_SETPOINT,HOMING,TELEOP
    }
    /**
     * The current state of the elevator
     */
    public States state;

    public boolean atMaxHeight = false;
    public boolean atMinHeight = false;

    /**
     * Whether Preferences or Constants should be used for PID values
     * <br />
     * <code>false</code> uses Constants.java for PID values
     * <code>true</code> uses NT Preferences for PID values with Constants.java as the fallback
     */
    public static final boolean ELEVATOR_USE_PREFERENCES_FOR_PID_VALUES = false;

    /**
     * Instance of Robot Preferences
     */
    public Preferences prefs;

    /**
     * Post Constants PID values to preferences
     * <br />
     * <i>Run this to initialize preferences or to make preferences up to date with the constants</i>
     */
    public static final boolean ELEVATOR_POST_PID_CONSTANTS_TO_NT_PREFERENCES = true;

    /**
     * <code>true</code> Disables intelligent control (PID, Setpoints, homing)
     * <br />
     * <code>false</code> Enables intelligent control (PID, Setpoints, homing) [SHOULD ALMOST ALWAYS BE SET TO]
     * <br />
     * <strong>This should <em>ONLY</em> be used for elevator testing and SHOULD NEVER BE ON DURING COMPETITION</strong>
     */
    public static final boolean DISABLE_INTELLIGENT_CONTROL = true;





    public Elevator() {
        prefs = Preferences.getInstance();
    
        elevatorMaster = new WPI_TalonSRX(Constants.ELEVATOR_MASTER_CANID);
        elevatorFollower = new WPI_VictorSPX(Constants.ELEVATOR_FOLLOWER_CANID);
        elevatorFollower.follow(elevatorMaster);
        if(ELEVATOR_POST_PID_CONSTANTS_TO_NT_PREFERENCES){
            prefs.putDouble("ELEVATOR_KP", Constants.ELEVATOR_KP);
            prefs.putDouble("ELEVATOR_KI", Constants.ELEVATOR_KI);
            prefs.putDouble("ELEVATOR_KD", Constants.ELEVATOR_KD);
            prefs.putDouble("ELEVATOR_KF", Constants.ELEVATOR_KF);
        }
        if(ELEVATOR_USE_PREFERENCES_FOR_PID_VALUES){
            elevatorMaster.config_kP(0, prefs.getDouble("ELEVATOR_KP",Constants.ELEVATOR_KP));
            elevatorMaster.config_kI(0, prefs.getDouble("ELEVATOR_KI",Constants.ELEVATOR_KI));
            elevatorMaster.config_kD(0, prefs.getDouble("ELEVATOR_KD",Constants.ELEVATOR_KD));
            elevatorMaster.config_kF(0, prefs.getDouble("ELEVATOR_KF",Constants.ELEVATOR_KF));

        }
        else{
            elevatorMaster.config_kP(0, Constants.ELEVATOR_KP);
            elevatorMaster.config_kI(0, Constants.ELEVATOR_KI);
            elevatorMaster.config_kD(0, Constants.ELEVATOR_KD);
            elevatorMaster.config_kF(0, Constants.ELEVATOR_KF);
        }
        this.state = States.TELEOP;
    }

    /**
     * Template for a setpoint
     */
    public class Setpoint{
        /**
         * Name or any notes regarding to the Setpoint
         */
        public String annotation;
        /**
         * The setpoint value
         */
        public int setpoint = -1;
        /**
         * The location within the Setpoint array
         */
        public int arrayIndex = -1;
        /**
         * Creates a new setpoint
         * @param annotation Name or any other useful information
         * @param setpoint The value of the setpoint
         * @param arrayIndex The index of the setpoint in the setpointsArray
         */
        public Setpoint(String annotation, int setpoint, int arrayIndex){
            this.setpoint = setpoint;
            this.annotation = annotation;
            this.arrayIndex = arrayIndex;

        }
    }
    
    public Setpoint[] setpointsArray = {new Setpoint("ABSOLUTE_BOTTOM", 0, 0),new Setpoint("SHIP_LOW",50,1),new Setpoint("ROCKET_LOW",100,2),new Setpoint("ROCKET_MEDIUM",200,3),new Setpoint("ROCKET_HIGH",300,4)};

    /**
     * Set the setpoint for the Talon SRX given the setpoint instance variable
     */
    public void updateSetpoint(){
        new ElevatorMoveToSetpoint().start();
    }
    /**
     * Set the setpoint for the Talon SRX
     * @param setpoint
     */
    public void updateSetpoint(int setpoint){
        this.setpoint = setpoint;
        this.updateSetpoint();

    }

    @Override
    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
        if(DISABLE_INTELLIGENT_CONTROL){
            setDefaultCommand(new ElevatorTeleop());
        }else{
            setDefaultCommand(new ElevatorAtSetpoint());
            new ElevatorHomingInit().start();
        }
        System.out.println(this.getDefaultCommandName());
        
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
        //updateSD();
        SmartDashboard.putString("ELEV COMMAND", this.getCurrentCommandName());
        SmartDashboard.putBoolean("Lower Limit Switch",this.lowerLimitSwitch.get());
        SmartDashboard.putBoolean("Upper Limit Switch",this.upperLimitSwitch.get());
        SmartDashboard.putBoolean("Intermediate Down",this.intermediateDownLimitSwitch.get());
        SmartDashboard.putBoolean("Intermediate Up",this.intermediateLimitSwitch.get());
        SmartDashboard.putNumber("ELEV ENC",this.elevatorMaster.getSelectedSensorPosition(0));


        if(this.intermediateLimitSwitch.get() && this.upperLimitSwitch.get() && !this.lowerLimitSwitch.get() && !this.intermediateDownLimitSwitch.get()){
            this.atMinHeight = true;
        }else{this.atMinHeight = false;}
        if(!this.intermediateLimitSwitch.get() && !this.upperLimitSwitch.get() && this.lowerLimitSwitch.get() && this.intermediateDownLimitSwitch.get()){
            this.atMinHeight = true;
        }else{this.atMinHeight = false;}
    }
    /**
     * Updates SmartDashboard
     */
    public void updateSD(){
        SmartDashboard.putNumber("ELEV/location", elevatorMaster.getSelectedSensorPosition(0));
        SmartDashboard.putNumber("ELEV/percentoutput",elevatorMaster.getMotorOutputPercent());
        SmartDashboard.putNumber("ELEV/setpoint",setpoint);
        SmartDashboard.putNumber("ELEV/setpointLevel",setpointLevel);
        SmartDashboard.putBoolean("ELEV/usingPreferencesForPIDValues", ELEVATOR_USE_PREFERENCES_FOR_PID_VALUES);
        SmartDashboard.putNumber("ELEV/error",elevatorMaster.getClosedLoopError());
        SmartDashboard.putNumber("ELEV/talontarget",elevatorMaster.getClosedLoopTarget());
        SmartDashboard.putString("ELEV/state",state.toString());
        SmartDashboard.putNumber("ELEV/activeTrajectoryVelocity",elevatorMaster.getActiveTrajectoryVelocity());
        SmartDashboard.putNumber("ELEV/outputCurrent",elevatorMaster.getOutputCurrent());
        SmartDashboard.putNumber("ELEV/outputVoltage",elevatorMaster.getMotorOutputVoltage());
        //SmartDashboard.putString("ELEV/homeState",hs.toString());

    }
    

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

