// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc100.Team100Robot.subsystems;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.ctre.phoenix.motorcontrol.LimitSwitchSource;
import com.ctre.phoenix.motorcontrol.LimitSwitchNormal;
import org.usfirst.frc100.Team100Robot.Constants;

import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.VictorSP;

/**
 *
 */
public class HatchPickup extends Subsystem {

    private WPI_TalonSRX tilt;
    private VictorSP roller;
    private Solenoid hatchFloorPickup;

    public HatchPickup() {
        tilt = new WPI_TalonSRX(Constants.HATCH_PICKUP_TILT_CANID);
        tilt.configForwardLimitSwitchSource(LimitSwitchSource.FeedbackConnector, LimitSwitchNormal.NormallyOpen);
        tilt.configReverseLimitSwitchSource(LimitSwitchSource.FeedbackConnector, LimitSwitchNormal.NormallyOpen);
        
        roller = new VictorSP(Constants.HATCH_PICKUP_ROLLER_PWM);
        addChild("Roller", roller);
        roller.setInverted(false);
        
        hatchFloorPickup = new Solenoid(Constants.PCM_CANID, Constants.HATCH_PICKUP_PCMID);
        addChild("HatchFloorPickup", hatchFloorPickup);
    }

    @Override
    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        // setDefaultCommand(new PickupHatch());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    public void intake(){
        roller.set(Constants.HATCH_PICKUP_INTAKE_SPEED);
    }

    public void stopRoller(){
        roller.set(0);
    }

    public boolean tiltUp(){
        System.out.println("STUFF");
        // if(tilt.getSelectedSensorPosition(Constants.HATCH_PICKUP_UPPER_LIMIT_SWITCH_SLOT) == 0) {
        //     tilt.set(ControlMode.PercentOutput, Constants.HATCH_PICKUP_TILT_SPEED);
        //     return false;
        // }
        // else return true;
        tilt.set(ControlMode.PercentOutput, Constants.HATCH_PICKUP_TILT_SPEED);
        return false;
    }

    public boolean tiltDown(){
        // if(tilt.getSelectedSensorPosition(Constants.HATCH_PICKUP_LOWER_LIMIT_SWITCH_SLOT) == 0) {
        //     tilt.set(ControlMode.PercentOutput, -Constants.HATCH_PICKUP_TILT_SPEED);
        //     return false;
        // }
        // else return true;
        tilt.set(ControlMode.PercentOutput, -Constants.HATCH_PICKUP_TILT_SPEED);
        return false;
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void updateDashboard(){
        SmartDashboard.putString(Constants.SB_GROUP_PREFIX_HATCH_PICKUP + "CurrentCommand", getCurrentCommandName());
        SmartDashboard.putNumber(Constants.SB_GROUP_PREFIX_HATCH_PICKUP + "Tilt/Voltage", tilt.getBusVoltage());
        SmartDashboard.putNumber(Constants.SB_GROUP_PREFIX_HATCH_PICKUP + "Tilt/Position", tilt.getSelectedSensorPosition());
        SmartDashboard.putNumber(Constants.SB_GROUP_PREFIX_HATCH_PICKUP + "Tilt/Velocity", tilt.getSelectedSensorVelocity());
        SmartDashboard.putNumber(Constants.SB_GROUP_PREFIX_HATCH_PICKUP + "Roller/Percent Output", roller.get());
        SmartDashboard.putNumber(Constants.SB_GROUP_PREFIX_HATCH_PICKUP + "Roller/Speed", roller.getSpeed());
        SmartDashboard.putBoolean(Constants.SB_GROUP_PREFIX_HATCH_PICKUP + "Solenoid Status", hatchFloorPickup.get());
    }
}

