// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc100.Team100Robot.subsystems;

import org.usfirst.frc100.Team100Robot.Constants;
import org.usfirst.frc100.Team100Robot.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.Solenoid;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 *
 */
public class Shifter extends Subsystem {

    private Solenoid driveTrainShifter;

    public Shifter() {
        driveTrainShifter = new Solenoid(Constants.PCM_CANID, Constants.DRIVETRAIN_SHIFTER_PCMID);
        addChild("DriveTrainShifter",driveTrainShifter);
    }

    @Override
    public void initDefaultCommand() {
        setDefaultCommand(new LowGear());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    public Solenoid getShifter(){
        return driveTrainShifter;
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void updateDashboard(){
        SmartDashboard.putString(Constants.SB_GROUP_PREFIX_SHIFTER + "Current Command", getCurrentCommandName());
        SmartDashboard.putBoolean(Constants.SB_GROUP_PREFIX_SHIFTER + "High Gear", driveTrainShifter.get());
    }
}

